VeterinaryClinicWeb/Controllers/DoctorController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using System.Linq;
using System.Threading.Tasks;
using VeterinaryClinicWeb.Models;
using VeterinaryClinicWeb.Models.EFRepository;
using VeterinaryClinicWeb.Models.ViewModels;

namespace VeterinaryClinicWeb.Controllers
{
    public class DoctorController : Controller
    {
        private EFDoctorRepository context;
        public DoctorController(VeterinaryClinicDbContext context)
        {
            this.context = new EFDoctorRepository(context);
        }

        public async Task<IActionResult> Index(int page=1)
        {
            int pageSize = 3;
            int count = await context.Doctors.CountAsync();
            IEnumerable<Doctor> items = await context.Doctors.Skip((page-1) * pageSize).Take(pageSize).ToListAsync();
            
            DoctorIndexViewModel doctorVM = new DoctorIndexViewModel()
            {
               Doctors = items,
               Pagination = new PageViewModel(count, page, pageSize)  
            };
            return View(doctorVM);
        }
    }
}

VeterinaryClinicWeb/Controllers/ServiceController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using VeterinaryClinicWeb.Models;
using VeterinaryClinicWeb.Models.EFRepository;
using Microsoft.EntityFrameworkCore;

namespace VeterinaryClinicWeb.Controllers
{
    public class ServiceController : Controller
    {
        private EFServiceRepository context;
        public ServiceController(VeterinaryClinicDbContext context)
        {
            this.context = new EFServiceRepository(context);
        }

        public IActionResult Index(string category = "no_category")
        {
            if (category == "no_category") 
                return RedirectToAction("Index", "Home");

            IEnumerable<Service> services = context.Services
                .Where(service => service.serviceCategory == category)
                .AsNoTracking()
                .ToList();

            return View(services);
        }
    }
}

VeterinaryClinicWeb/Views/Shared/Components/Carousel.cshtml
<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="carousel">
    <div class="carousel-indicators">
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
        <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
    </div>
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="/images/carousel/dog1.jpg" class="d-block w-100 carousel-pic-size" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>First slide label</h5>
                <p>Some representative placeholder content for the first slide.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="/images/carousel/dog2.png" class="d-block w-100 carousel-pic-size" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Second slide label</h5>
                <p>Some representative placeholder content for the second slide.</p>
            </div>
        </div>
        <div class="carousel-item">
            <img src="/images/carousel/combo1.jpg" class="d-block w-100 carousel-pic-size" alt="...">
            <div class="carousel-caption d-none d-md-block">
                <h5>Third slide label</h5>
                <p>Some representative placeholder content for the third slide.</p>
            </div>
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

VeterinaryClinicWeb/Views/Shared/Components/Footer.cshtml
<div class="container">
    <div class="col">
        <div class="container-fluid footer-block">
            <div class=row>
                <div class="col-12 col-md-4">
                    Тут має бути номер телефону х2, емейл адреси, можливо посилання на соціальну мережу, фізична адресу ТУ
                </div>
                <div class="col-12 col-md-4">
                    Тут має бути номер телефону х2, емейл адреси, можливо посилання на соціальну мережу, фізична адресу ТУ
                </div>
                <div class="col-12 col-md-4">
                    Тут має бути номер телефону х2, емейл адреси, можливо посилання на соціальну мережу, фізична адресу ТУ
                </div>
            </div>
        </div>
    </div>
</div>

VeterinaryClinicWeb/Views/Shared/Components/GlobalNavbar.cshtml
@inject IConfiguration Configuration
@{
    string clinicName = Configuration["VeterinaryClinicInfo:VeterinaryClinicName"];
}

<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container-fluid">
            <a class="navbar-brand" href="/">@clinicName.ToUpper()</a>
            <button class="navbar-toggler" 
                    type="button" 
                    data-bs-toggle="collapse" 
                    data-bs-target="#navbarNavDropdown" 
                    aria-controls="navbarNavDropdown" 
                    aria-expanded="false" 
                    aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse ms-auto" id="navbarNavDropdown">
                <ul class="navbar-nav ml-auto w-100 justify-content-end">

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle"
                           href=""
                           id="OrdersDropDown"
                           role="button"
                           data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Orders
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="OrdersDropDown">
                            <li><a class="dropdown-item" 
                             asp-controller="Order" 
                             asp-action="Create">
                             New order
                             </a></li>
                            <li><a class="dropdown-item"
                             asp-controller="Order" 
                             asp-action="Check">Check order</a></li>
                        </ul>
                    </li>

                    <li class="nav-item">
                        <a class="nav-link" asp-controller="Doctor" asp-action="Index">Doctors</a>
                    </li>

                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" 
                           id="ServicesDropDown" 
                           role="button" 
                           data-bs-toggle="dropdown" 
                           aria-expanded="false">
                            Services
                        </a>

                        <ul class="dropdown-menu" aria-labelledby="ServicesDropDown">
                            @foreach (var enumItem in Enum.GetValues(typeof(ServiceCategory)))
                            {
                                <li><a class="dropdown-item"
                                asp-controller="Service" 
                                asp-action="Index"
                                asp-route-category="@enumItem">@enumItem.ToString().CapitalizeFirstLetter()</a></li>
                            }
                        </ul>
                    </li>

                </ul>
            </div>
        </div>
    </nav>
</div>

VeterinaryClinicWeb/Views/Shared/Components/Pagination.cshtml
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <li class="page-item"><a class="page-link" href="#">Previous</a></li>
    <li class="page-item"><a class="page-link" href="#">1</a></li>
    <li class="page-item"><a class="page-link" href="#">2</a></li>
    <li class="page-item"><a class="page-link" href="#">3</a></li>
    <li class="page-item"><a class="page-link" href="#">Next</a></li>
  </ul>
</nav>